version: "3.4"

networks:
  go-graphql-react:
    driver: bridge

services:
  web:
    image: go-graphql-react
    build:
      context: .
    restart:
      always
    ports:
      - "3000:3000"
    environment:
      - "POSTGRES_URL=postgres://go-graphql-react:password@go-graphql-react-postgres:5432/go-graphql-react?sslmode=disable"
      - "POSTGRES_MIGRATIONS_FILE_URL=file:///migrations"
    networks:
      - go-graphql-react
    depends_on:
      - go-graphql-react-postgres

  go-graphql-react-postgres:
    container_name: go-graphql-react-postgres
    image: postgres
    environment:
      - "POSTGRES_USER=go-graphql-react"
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_DB=go-graphql-react"
    networks:
      - go-graphql-react
    ports:
      - "5432:5432"
