output   = "internal/models/db"
wipe     = true
no-tests = true

[psql]
  dbname = "postgres"
  host   = "localhost"
  port   = 5432
  user   = "postgres"
  pass   = "postgres"
  schema = "public"
  blacklist = ["schema_migrations"]
