// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type UserInput struct {
	Name     *string `json:"name"`
	Email    string  `json:"email"`
	Password string  `json:"password"`
}
